name: "github-ejs-build"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install prerequisites
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
            JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: NPM Installation 
        run: |
          jf npmc --repo-resolve dro-npm-unsecure-remote
          # 
          jf npm ci
          jf audit --npm