name: "github-ejs-build"
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Here we install all the tools : docker buildx, QEMU, JDK 11, JFrog CLI
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install prerequisites
      - name: Install Node
        uses: actions/setup-node@v3
        with:
            node-version: 18
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
            JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
      - name: NPM Audit 
        env:
          JFROG_CLI_BUILD_NAME: 'github-ejs-demo'
          JFROG_CLI_BUILD_NUMBER: ''
        run: |
          jf rt bce ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }}
          jf rt bag ${{ env.JFROG_CLI_BUILD_NAME }} ${{ env.JFROG_CLI_BUILD_NUMBER }}
          jf npmc --repo-resolve dro-npm-unsecure-remote
          jf npm ci --only=production --omit=dev --build-name=${{ env.JFROG_CLI_BUILD_NAME }} --build-number=${{ env.JFROG_CLI_BUILD_NUMBER }}
          jf audit --npm
      - name: Docker build 
        run: |
          docker build . -t ejs-app:$JFROG_CLI_BUILD_NUMBER
          docker tag ejs-app:$JFROG_CLI_BUILD_NUMBER $JF_HOST/dro-backend-docker-dev-local/ejs-app:$JFROG_CLI_BUILD_NUMBER
          jf docker push $JF_HOST/dro-backend-docker-dev-local/ejs-app:$JFROG_CLI_BUILD_NUMBER --build-name=$JFROG_CLI_BUILD_NAME --build-number=$JFROG_CLI_BUILD_NUMBER 
          jf rt bp --build-name=$JFROG_CLI_BUILD_NAME --build-number=$JFROG_CLI_BUILD_NUMBER
